[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  # All environment variables must be configured in Netlify UI (Site settings > Build & deploy > Environment):
  # VITE_SUPABASE_URL
  # VITE_SUPABASE_ANON_KEY (public anon; still manage centrally, not committed)
  # VITE_DEEPSEEK_API_KEY (secret)
  # VITE_DEEPSEEK_API_URL (optional override; defaults to provider URL)
  # Additional optional keys: VITE_SUPABASE_JWT_KID, VITE_SUPABASE_JWT_JWK
  # Intentionally left blank to avoid committing any values.